#!/usr/bin/env bash
# Install nginx server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /usr/html/index.html
sudo service nginx restart
