#!/usr/bin/env bash
# Install Nginx and redirect a page.
apt-get update && apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
service nginx restart
sed -i '/listen \[::\]:80 default_server;/aadd_header X-Served-By $hostname;\nlocation /redirect_me {\nrewrite ^ https://www.youtube.com/watch?v=dJMVtwbriK0 permanent;\n}\n\nerror_page 404 /custom_404.html;\nlocation = /custom_404.html {\ninternal;\n}' /etc/nginx/sites-available/default
service nginx restart
