#!/usr/bin/env bash
# Install and Configure HAproxy on lb-01.
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo 'ENABLED=1' |sudo tee -a /etc/default/haproxy
sudo echo "
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 2003-web-01 35.196.29.78:80 check
    server 2003-web-02 35.231.126.72:80 check
"    | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart 
