#!/usr/bin/env bash
# Show 10 times a message "Holberton School" in 4 item Show bad luck, in 8 item Show good luck.

Cont=0
while [  $Cont -lt 10 ]; do
	if [ $Cont -eq 3 ]
	then
	echo "bad luck"
	elif [ $Cont -eq 7 ]
	then
	echo "good luck"
	else
		echo "Holberton School"
	fi
	let Cont=Cont+1
done


=================================
#!/usr/bin/env bash
#Prints bad luck on 4 and good luck on 8
COUNT=1
while [ $COUNT -le 10 ]; do
    if [ $COUNT -eq '4' ]
    then
	echo "bad luck"
    elif [ $COUNT -eq '8' ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let COUNT=COUNT+1
done

=================================
#!/usr/bin/env bash
# Thi script loops from 1 to 10. It prints "bad luck" the 4th iteration, "good luck" the 8th iteration, and "Holberton School for all others.
i=1
while (( i <= 10 ))
do
	if (( i == 4 ))
	then
		echo "bad luck"
	elif ((i == 8 ))
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	i=$(( i + 1 ))
done


=================================

# This script prints "Holberton School" 10 times, but prints out "bad luck" on
# the 4th iteration and "good luck" on the 8th iteration
I=1
while [ $I -le 10 ];
do
	if [ $I = 4 ]; then echo "bad luck";
	elif [ $I = 8 ]; then echo "good luck";
	else echo "Holberton School"
	fi
	I=$(( I + 1 ))
done

=================================

#!/usr/bin/env bash
# Loops from 1 to 10
# Display "bad luck" for 4th loop iteration
# Display "good luck" for 8th loop iteration
# Display "Holberton School" for other iterations

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School" 
	fi
	(( ++i ))
done

=================================


#!/usr/bin/env bash
# Loops from 1 to 10, prints different msg

COUNTER=1
while [ $COUNTER -lt 11 ]; do
      if [ $COUNTER -eq 4 ]
      then
	echo "bad luck"
      elif [ $COUNTER -eq 8 ]
      then
      	echo "good luck"
      else
	echo "Holberton School"
      fi
      let COUNTER=COUNTER+1
done
