#!/usr/bin/env bash
# Counter 1 to 20 with intereaction of messages in 4, 9, 17 loop.

Cont=1
while [ $Cont -le 20 ]
do
	echo $Cont
	case $Cont in
		4 ) echo "bad luck from China";;
		9 ) echo "bad luck from Japan";;
		17 ) echo "bad luck from Italy";;
	esac
	let Cont=Cont+1
done
