#!/usr/bin/env bash
# Changes hosts file localhost facebook 

HOLD=/etc/hosts
HNEW=~/hosts.new
LC="127.0.0.2	localhost"
FB="8.8.8.8	facebook.com"
cp -f  "$HOLD" "$HNEW"

sed -i '/localhost/d' $HNEW
sed -i '/facebook.com/d' $HNEW

echo "$LC" >> $HNEW
echo "$FB" >> $HNEW

cp -f "$HNEW" "$HOLD"

rm -f "$HNEW"
