#!/usr/bin/env bash
# Run user'nginx' in nginx
pkill apache2
chmod 766 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/sites-available/default
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
